#!/bin/bash
#
# setup-bitwarden-helium-biometrics.sh
#
# Wires up native messaging between the Bitwarden desktop Flatpak and the
# Helium browser, so the Bitwarden browser extension can use biometric
# unlock via the desktop app.
#
# Background: Bitwarden's desktop app writes native messaging manifests
# for browsers it recognizes (Chrome, Chromium, Brave, Edge, Vivaldi...).
# Helium isn't one of them, so the extension can never find the desktop
# app and "Unlock with Biometrics" stays greyed out. This script creates
# the manifest by hand and points it at a small launcher that runs the
# Bitwarden Flatpak's desktop_proxy binary inside the same sandbox as the
# running desktop app.
#
# Prerequisites (do these once, manually, before running this script):
#   - Bitwarden desktop Flatpak installed and biometric unlock already
#     working for the desktop app itself (system authentication / polkit
#     policy already in place).
#   - Helium installed, with the Bitwarden extension added from the
#     Chrome Web Store.
#   - In Helium: helium://extensions -> Bitwarden -> "Allow access to
#     file URLs" turned on.
#
# After running this script:
#   1. Fully quit Helium (not just close the window).
#   2. Open the Bitwarden desktop app and unlock it.
#   3. Launch Helium, open the Bitwarden extension, Settings ->
#      Account security -> "Unlock with biometrics". Approve the
#      "communicate with cooperating native applications" prompt.
#
# Safe to re-run; it will overwrite the launcher and manifest with
# current values.

set -euo pipefail

FLATPAK_APP_ID="com.bitwarden.desktop"
HELIUM_CONFIG_DIR="${HOME}/.config/net.imput.helium"
LAUNCHER_DIR="${HOME}/.local/libexec"
LAUNCHER_PATH="${LAUNCHER_DIR}/bitwarden-proxy"
MANIFEST_DIR="${HELIUM_CONFIG_DIR}/NativeMessagingHosts"
MANIFEST_PATH="${MANIFEST_DIR}/com.8bit.bitwarden.json"

# Chrome Web Store extension ID for Bitwarden. Override if you sideload
# a different build (e.g. self-built or a different extension ID).
BITWARDEN_EXTENSION_ID="${BITWARDEN_EXTENSION_ID:-nngceckbapebfimnlniiiahkandclblb}"

echo "==> Checking for Bitwarden Flatpak (${FLATPAK_APP_ID})..."
if ! flatpak info "${FLATPAK_APP_ID}" >/dev/null 2>&1; then
    echo "ERROR: ${FLATPAK_APP_ID} is not installed as a Flatpak." >&2
    exit 1
fi

echo "==> Locating desktop_proxy inside the Flatpak sandbox..."
PROXY_PATH="$(flatpak run --command=sh "${FLATPAK_APP_ID}" -c \
    'find /app -iname "*desktop_proxy*" -type f 2>/dev/null | head -n1')"

if [[ -z "${PROXY_PATH}" ]]; then
    echo "ERROR: could not find desktop_proxy inside ${FLATPAK_APP_ID}." >&2
    echo "       Check for a Bitwarden update; the binary path/name may have changed." >&2
    exit 1
fi
echo "    Found: ${PROXY_PATH}"

echo "==> Writing launcher script: ${LAUNCHER_PATH}"
mkdir -p "${LAUNCHER_DIR}"
cat > "${LAUNCHER_PATH}" <<EOF
#!/bin/bash
# Runs Bitwarden's native messaging bridge inside the Flatpak sandbox so
# it can reach the desktop app's IPC socket. Generated by
# setup-bitwarden-helium-biometrics.sh; do not edit by hand, re-run the
# generator script instead.
exec flatpak run --command="${PROXY_PATH}" "${FLATPAK_APP_ID}" "\$@"
EOF
chmod +x "${LAUNCHER_PATH}"

echo "==> Writing native messaging manifest: ${MANIFEST_PATH}"
mkdir -p "${MANIFEST_DIR}"
cat > "${MANIFEST_PATH}" <<EOF
{
  "name": "com.8bit.bitwarden",
  "description": "Bitwarden desktop <-> browser bridge",
  "path": "${LAUNCHER_PATH}",
  "type": "stdio",
  "allowed_origins": ["chrome-extension://${BITWARDEN_EXTENSION_ID}/"]
}
EOF

echo "==> Done."
echo "    Launcher:  ${LAUNCHER_PATH}"
echo "    Manifest:  ${MANIFEST_PATH}"
echo
echo "Next steps:"
echo "  1. Fully quit Helium."
echo "  2. Open and unlock the Bitwarden desktop app."
echo "  3. Launch Helium, open the Bitwarden extension, and enable"
echo "     'Unlock with biometrics' in Settings -> Account security."
