FROM mcr.microsoft.com/devcontainers/base:ubuntu-24.04

ARG TARGETARCH=amd64

RUN apt-get update && apt-get install -y \
    curl \
    wget \
    tar \
    unzip \
    ca-certificates \
    gnupg \
    bash-completion \
    skopeo \
    && rm -rf /var/lib/apt/lists/*
